### PR TITLE
015/master

### PR DESCRIPTION
**Pull request by raq929**
Updates from challenge and node templates.
Adds tests.
Updates README.

### CODE REVIEW

**Comment by gaand** [comment]
The branches should only differ in one file:

```diff
  $ git diff 015/master 015/solution --name-status 
-M       README.md
 M       lib/atc.js
-M       spec/atc.spec.js
```

Also, the example files should be deleted and in file names, `atc` should be `challenge`.

**Comment by raq929** [comment]
Ok. I believe both those issues are now resolved.

**Comment by raq929** [comment]
This is updated so it no longer dictates HOW you choose to store your queue; instead, it requires an aircraftCount function.

**Comment by gaand** [comment]
```sh
 $ git diff 015/master 015/solution --name-status 
M       README.md
M       lib/challenge.js
M       spec/challenge.spec.js
```

**Comment by raq929** [comment]
Ack! I was doing that so faithfully for a while. Fixed.

**Pull request merged**
